version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_DB=customers
      - POSTGRES_USER=tetiana
      - POSTGRES_PASSWORD=password

  application:
    build: .
    image: customers-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customers
      - SPRING_DATASOURCE_USERNAME=tetiana
      - SPRING_DATASOURCE_PASSWORD=password

    depends_on:
      - postgres